<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La hidalga y el mapache</title>
</head>
<body>
    <p>Erase una vez, en un pueblito en el oeste de Francia, donde una joven hidalga vivia en una gran cabaña, con fogata y todo lo que pudiese necesitar. Ella vivia con su esposo en esa cabaña. Cada mes, ella hacia un largo recorrido por el bosque de Ouvearts para ir a la pequeña choza donde vivia su mama con su hermano pequeño. El camino era peligroso, aun asi, la hidalga nunca estuvo en peligro alguna vez. Un dia, aproximadamente por inicios de noviembre, la joven hidalga iba caminando por el estrecho sendero del bosque, con las hojas que caian y yacian rojas y marrones. Hasta que, de repente, un sonido extraño que provenia desde un arbustoo la espanto. La hidalga se asusto un monton, pero tuvo el coraje de ver quien estaba escondido en ese arbusto. Al acercarse al arbusto, vio un pequeño y adorable mapache, que estaba comiendo de los frutos que caian del arbol que estaba arriba del arbusto. La hidalga se lleno de ternura, sin embargo, tuvo que seguir su camino, o sino llegaria tarde a casa de su madre.</p>
        <img style="width:500px; height:500px;" src="img/hid-img_2.png" alt="">
    </div>
    <div>
    <p>Pronto, la hidalga llego a la choza de su madre. Y permanecio toda la noche en esta. Mientras dormia, un ruido perturbador de disparo la desperto. La hidalga estaba atormentada, ella odiaba a los cazadores, pero ella ignoro los sonidos y siguio con su sueño. Cuando el sol se levanto, la hidalga tomo sus cosas y se dirigio a la casa de su marido. Mientras iba caminando el mismo mapache que vio el dia pasado se le acerco y empezo a rasgar su vestido, emitiendo unos sonidos. La hidalga no sabia que ocurria. El mapache se fue corriendo hacia un rincon, a lado de un arbusto y la hidalga lo siguio. Cuano la hidalga llego, se quedo perpleja. Un venado yacia muerto en la hierba. Pues ya entendia de que se habian tratado los disparos. Aun asi, la hidalga siguio su camino. Tras el pasar de los dias, en su camino de ir a la casa de su marido y luego a la de su madre no vio al mapache pero cuando iba de regreso a la casa de su esposo el mapache la detuvo. Sus ojos estaban llorosos, y emitia gemidos de dolor y tristeza. La hidalga se impacto. Por lo que siguio al mapache hacia donde iba.</p>
        <img style="width:500px; height:500px;" src="img/hid-img_3.png" alt="">
    </div>
    <div>
    <p>Caminaron por unos cinco minutos hasta llegar a una pequeña boveda la cual estaba abierta. La hidalga se asomo para ver que habia adentro y se sorprendio al descubrir que eran armas. La hidalga estaba frustrada, ella estaba dispuesta a denunciar ante el gobierno cualquier acto de caceria ilegal que este ocurriendo. Junto con el mapache fueron a la casa de su esposo, donde la hidalga le conto todo lo sucedido. El esposo se sorprendio ante la maldad a la que puede llegar una persona, y que quien sea que haya hecho eso, es una persona atroz. La hidalga se alegro por lo que habia dicho su esposo pero el mapache estaba incomodo, y alterado. Algo le estaba pasando. Aun asi almorzaron juntos y luego la hidalga regreso con el mapache a casa. Mientras iban por el sendero el mapache se quedo en el arbusto y la hidalga siguio con su camino, pero se le quedaron sus cosas en el suelo de alli. Ya cuando estaba oscuro, y la hidalga ya habia llegado a la casa, se percato de que no encontraba sus cosas, por lo que regreso para ir a ver sus cosas. Pero cuando llego vio a su esposo con un rifle y a el mapache herido. La hidalga se quedo boquiabierta. Su propio esposo le mintio y resulto que era el cazador. La hidalga no lo penso dos veces y se lanzo encima de su esposo. Ella empezo a golpearlo. Pero el esposo le dijo que pare, que no queria hacerle daño. Aun asi, la hidalga siguio atacando hasta que el esposo se canso. Empujo a la hidalga y disparo su rifle. La bala roso el hombro de la hidalga y dio contra un arbol. "Como te atreves..." dijo la hidalga y se arrodillo y empezo a llorar. Pero con sus lagrimas el mapache abrio los ojos y la hidalga se cautivo. El esposo le dijo que se alejara, que iba a acabar con el, pero la hidalga le menciono dos cosas, una que no iban a ser esposos mas, y de que era inhumano. En su intensa discusion, el mapache salto hacia la cara del esposo y rasguño su cara. El cazador gritaba de agonia. La hidalga aprovechando esto empujo al cazador a hoyo que se encontraba a cortos metros de ella. El cazador cayo, y sus gritos resonaban como eco. Demoro veinte segundos en caer, asegurando su muerte. La hidalga se encontraba perturbada, pero a la vez feliz por haber salvado al mapache. Poco despues la hidalga lo tuvo como mascota y viveron en la choza junto a su madre.</p>
        <img style="width:500px; height:500px;" src="img/hid-img_3.png" alt="">
    </div>
    <footer>Derechos reservados, Mario Hernandez, 2024</footer>
</body>
</html>