<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Ultima Generacion</title>
</head>
<body>
<div>
        <h1>La Ultima Generacion</h1>
    </div>
    <div>
        <p>En un lugar indefinido de la galaxia, la estatuilla del conocimiento, construida por una civilizacion alienigena en Saturno se extravio. Volo, y volo por el espacio hasta llegar a la tierra. Un niño la encontro en el jardin de su madre, en el campo. Estaba hecha añicos, por lo que la repusieron y les dieron mucho dinero por la estatuilla. El estado decidio averiguar para que servia esta, pero no lo pudieron decifrar, asi que le dieron la estatuilla a un experto en decifrar mensajes ocultos, llamado Liam. Liam se llevo la estatuilla a su casa para intentar resolverla. Pero en eso, la estuatilla se junta por su misma cuenta y le cuenta a Liam que el fin del mundo llegara a la tierra, y que son "La Ultima Generacion". Liam estaba asustado. No podia creer lo que estaba viendo. Una estatuilla hablando por su cuenta anunciandole el fin de su amada tierra. Liam se alejo de la estatuilla, pero la estatuilla abrio un cajon en su pecho y absorbio a Liam. El desaparecio de repente. Nadie sabia en el mundo lo que habia pasado, por lo que el fin del mundo los iba a atrapar desapercibidos. En muchos lugares de la tierra, la gente se encontraba feliz, disfrutando de la vida, creando planes para un futuro, y divirtiendose, pero ellos no sabian que un armagedon estaba a punto de comenzar.</p>
        <img style="width:500px; height:500px;" src="img/coz-img_1.png" alt="">
    </div>
    <div>
        <p>La estatuilla permanecio en la casa de Liam, quieta y rigida como una roca. Pero un 9/12/2060 la estatuilla se convirtio en un titan gigante y temible que azoto las ciudades de Paris y Estrasburgo, luego se dirijo a Munich, hasta darse por muerto en Berlin, asesinado por los soldados alemanes. La destruccion que causo el titan fue severa. La torre eiffel habria sido tumbada, el museo de Louvre fue aplastado, y todos los sitios hermosos que habian en estas ciudades fueron amasacrados.Despues de el lapso de dos meses, una tormenta gigante llego a Miami, con vientos tremendamente fuertes que levantaban una casa entera por los aires. El mar se desbordo causando una inundacion letal en toda Florida y muertes abundantes en este. Luego la tormenta se desplazo hasta New Orleans, Missisipi, Tijuana y Guatemala, arrasando estos paises, dejando millones de muertos. Toda esta tragedia ocurrio un febrero de 2061, entre los dia 5-21. Poco despues, en marzo, se reporto el brote de una epidemia en Seul, la cual se expandio hasta llegar a ser una pandemia. La enfermedad era extraña, los infectados se volvian dementes y atacaban a la gente, como zombies, pero mas rapidos, fuertes, inteligentes y perspicaces. La enfermedad perduro por 3 años, hasta el 2064, hasta que fue erradicada con una vacuna creada en Toronto. A pesar de la creacion de la cura, mas de un cuarto de la poblacion murio por esta pandemia. Ya que los doctores se vieron obligados a extreminar a los infectados, ya que no habia otra opcion. Al darse tanta destruccion, se llevaron a todas las personas menores de 18 años en todo Estados Unidos, y las ubicaron en un bunker donde los cuidaban, pero eran sometidos a experimentos. Regina, era una chica de 14 años que habia sido encerrada en el bunker, ya estaba harta de los experimentos que les hacian, asi que creo una revolucion junto a sus mejores amigos, Trevor, que tenia 13 años, Nadia, que tenia 14 años, Dayanna, que tenia 13 años, y otros chicos mayores y menores que ellos. Dayanna se infiltro al cuarto de armas, donde robo rifles y granadas para armar el motin. Se los entrego a sus compañeros y salieron al ataque. A pesar de que mataron a muchos de los guardias. Uno de ellos mato a Nadia, sin piedad, dejando a Regina triste.</p>
        <img style="width:500px; height:500px;" src="img/coz-img_2.png" alt="">
    </div>
    <div>
        <p>Despues de lo ocurrido, mato al guardia responsable del asesinato. Y se marcharon a una zona segura (un apartamento abandonado, pero aun con recursos). En junio de 2064, un terremoto sacudio fuertemente Rabat, capital de marruecos, el terremoto fue tan fuerte que se sintio hasta el otro hemisferio. Este terremoto causo replicas muy fuertes que se presenciaron en Nueva York, Alexandria, Amsterdam, Nueva Dehli y Tokyo. En una de las replicas, en Nueva York, el apartamento donde vivian los chicos que se liberaron del bunker se tumbo, matando a todos, excepto a Regina y un chico mas llamado Uriel, que tenia 14 años. Regina se encontraba muy triste por lo ocurrido pero Uriel la consolo, le dijo que le iba a hacer compañia para sobrevivir a esto. Unos dias despues un tsunami gigante llego a Tokyo, tragandose todo Japon, e inundando gran parte de Corea y China. Tambien despues los volcanes en todo el mundo explotron sin control, llenando de cenizas todo el mundo y oscureciendolo. El mundo se encontraba en un total caos, no habia lugar seguro. Hasta que un dia una explosion enorme se produjo en el medio oriente que mato a todos. Despues de todo lo ocurrido, Regina desperto, y vio a Uriel muy herido por lo que lo llevo a un lugar seguro. Recorrieron kilometros, pero no encontraron ayuda, los bunkers estaban destrozados, no habia nadie. Hasta que despues de tanto caminar, encontraron un pequeño bunker, donde salieron mas chicos que no eran mayores de 20 años, que atendieron a Uriel y acogieron a Regina en el bunker. Pues decidieron esconderse alli hasta que la tierra vuelva a ser normal, y Regina dijo: "Definitivamente, somos la Ultima Generacion..."  </p>
        <img style="width:500px; height:500px;" src="img/coz-img_3.png" alt="">
    </div>
    <footer>Derechos reservados, Mario Hernandez, 2024</footer>
    </body>
</html>