<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mitologia Coceza</title>
</head>
<body>
<div>
        <h1>Mitologia Coceza</h1>
    </div>
    <div>
        <p>En un tiempo indefinido dentro de un lapso infinito de tiempo, un titan llamado Urell vivia en un lugar tan alto, que sobrepasaba el Cosmos, mientras su hermano Deivar, era un titan que dormia bajo un oceano oscuro y caotico, no habia nada, y se llamaba "Rogteh". Urell sobrevolaba los cielos del Cosmos con su nube voladora y daba un paseo por todo este siempre. Un dia, Urell se sentia solo, pues no habia nadie quien lo acompañe, pues lo que hizo fue crear un universo gigantesco y prospero, donde iba a crear varias masas de tierra, roca y gas para formar lugares donde la vida pueda prosperar, y eso es lo que iba a pasar. Urell creo la vida en un planeta, que tenia condiciones hospitas para vivir, pero de la nada, emergio un titan creado por el polvo que le advirtio de que el y toda su familia iban a morir y que iba a destruir lo que mas aprecia. Urell, con cara de rechazo, ignoro al titan que se desvanecio. Despues, Urell hundio sus dedos en el monton de polvo que yacia en el planeta, y se crearon la tierra, luego lloro de tanta felicidad que creo charcos gigantescos en la interseccion de las tierras, creando los mares, rios y lagos, despues mando una carga de energia sobre todo lo creado, y se creo la vida. Plantas, animales, monstruos y de todo. Urell se sentia orgulloso de su creacion, pero luego sintio de que estas criaturas eran incapaces de progresar en la sociedad, por lo que creo a una especie inteligente, un humano, de hecho, humanos, ya que creo un hombre y una mujer, para que asi la descendencia se multiplique. En ese momento, el titan hizo su segunda aparicion, pero antes de que pueda decir una palabra, Urell lo mato, estaba harto de lo que le decia, pues le daba mucha intriga. Con el cuerpo del titan fue al centro del universo, ya que yacia apagado y oscuro, por lo tanto, creo con el cuerpo del titan, un brillante mundo, con una estructura ferrea hecha de las piedras mas preciosas, y decidio que ahi el haria una descendencia de dioses, para proteger a la humanidad. Llamo a ese mundo, Midharv.</p>
        <img style="width:500px; height:500px;" src="img/coz-img_1.png" alt="">
    </div>
    <div>
        <p>Luego una gran descendencia amplio, junto a dioses como Edzeon, el dios del sol y la verdad, Weatk, la diosa del mar y la prosperidad, Qhen, el dios del caos y la desesperacion, Fexendj, el dios del inframundo y los muertos, Trea, diosa de la luna y de la amistad y Uja, diosa del amor y la belleza. Ademas, hay dioses que tambien intervienen como Hion, dios de la estrategia y la guerra y Rehvalek, dios de la sabiduria y pensamiento. En adicion, tambien hay semidioses que aportaron mucho como Jytron, que era un semidios que protegia a la humanidad de criaturas monstruosas, matandolas y encerrandolas en una mazmorra llamada "Extraik", donde todos estos monstruos eran encerrados. Tambien habia una semidiosa llamada Cetaf, que cuidaba Midharv y observaba que todo vaya bien en el Cosmos. Los dioses tuvieron miles de descendientes, pero una en espcifico marco la historia de todo esto. Era Juwa, la diosa de la magia y el arte, era una diosa muy amable, pero ciertas veces rencorosa. Era hija de Qhen y Uja, y era a la que menos la querian, pues no era muy util para ellos. Juwa estaba muy triste por esto, por lo que desperto a Deivar, desde las tinieblas maritimas y se casaron. Tuvieron aproximadamente veinte mil hijos, en los que se incluian bestias maritimas, terrenales, dioses del caos y refihas, que eran criaturas con orejas gigantes, tres ojos y cuerpo de lobo y leon.</p>
        <img style="width:500px; height:500px;" src="img/coz-img_2.png" alt="">
    </div>
    <div>
        <p>En estos años, la humanidad prospero hasta llegar a la actualidad y los dioses han dado advertencias de el proximo apocalipsis. Segun profecias, Deivar y Juwa iran con sus hijos hacia Midharv destruyendo todo a su paso, incluyendo el mundo de los muertos (Veihayta), el palacio de los dioses (Jigglap) y los mares (Wookooev). Uno de los hijos de Deivar, para ser especifico Yhuya, la dragona gigante, se comera el sol, y Kmnathgio, el gigante carnivoro, se comera la luna. El mundo caera en oscuridad y Juwa matara a la mayoria de los dioses. Las muertes de los dioses seran fatales, Urell y Deivar en forma de dragones marinos se mataran a si mismos en una batalla titanica provocando una cadena de olas de tamaño colosal que azotaran el universo (y la tierra por su puesto). Edzeon morira devorado por Uhu, el reptil gigante. Weatk morira hechizada por Juwa, el hechizo sera irse encogiendo hasta ser del tamaño de una hormiga, hasta que Juwa la aplaste. Qhen morira tirado en el vacio (Ophh) por su propia hija (Juwa). Fexendj morira por una explosion de sangre de Yhuya, la cual sera venenosa, que quemara a Fexendj y a sus hijos hasta dejar solo sus cenizas. Trea sobrevivio. Hion morira apuñalado con la espada de la venganza, que absorbia el poder de todos los dioses. Rehvalek sobrevivo. Tambien habran semidioses que moriran como Jytron que morira aplastado por un monte y Cetaf, que morira devorada por Deivar, en forma de bestia. Todos los mencionados solo son unos pocos de los fallecidos, tanto como otros dioses y sus generaciones murieron. Cuando el apocalipsis termine, las bestias pereceran, y formaran mundos nuevos. Neve, la diosa de la paz y tranquilidad, se encargara de proteger a los difuntos en el valle de Ghihie, junto a los hijos de Edzeon. Los otros sobrevivientes, Rehvalek y Trea se casaran y reinaran en el paraiso. Hojo, el dios mensajero, que tambien sobrevivio, se dirigira a las profundidades del mar y recuperara la cabeza de Urell, al plantarla sobre la tierra, todos los mundos se iluminaran de belleza y vida, no habra muerte ni maldad, todos seran felices. Se presume que Deivar despertara millones de años despues, pero por el momento, nadie sabe...  </p>
        <img style="width:500px; height:500px;" src="img/coz-img_3.png" alt="">
    </div>
    <footer>Derechos reservados, Mario Hernandez, 2024</footer>
    </body>
</html>