<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Percy Jackson, el Multiverso Mitologico</title>
</head>
<body>
<div>
<h1 style="text-align:center;">Percy Jackson y el Multiverso Mitologico</h1>
<p style="text-align: justify;">Hace un par de semanas, me encontraba durmiendo en la cabaña 3, en el campamento mestizo, pero sentia un mal presentimiento, me sentia observado. Desde que Luke se revelo, y desaparecio en el portal, me ha causado mucha incertidumbre lo que podria pasar. Esa misma noche no podia dormir, por lo que sali para observar el bosque y caminar un poco. La noche era fria y melancolica, para nada me tranquilizaba pero la acohedora brisa me hacia retractar. De repente, cuando pase por el arroyo, una ninfa del bosque me dijo con un tono fuerte y brusco: "No deberias estar despierto a estas horas chico." La verdad, tenia razon, eran las 4AM y tenia que estar durmiendo para estar como nuevo el siguiente dia (entrenamiento), por lo que le respondi con un "Ok", y volvi a mi recamara. Sinceramente no tenia sueño, por lo que me comi unos dulces que tenia en la mochila, al comermelos, la energia me subio exageradamente, y me sentia tan energico que no podia dejar de moverme. En ese lapso de tiempo, escuche unos golpes afuera del campamento mestizo. Eran golpes de magnitud descomunal, que hicieron temblar todo el campamento.</p> 
            
<p style="text-align: justify;">Mi corazon latia a mil por hora, estaba muy asustado, no sabia que pasaba hasta que sali y me di cuenta de que ocurria. Era Cronos, de alguna manera venia con Luke, Ares, Hades y grandes bestias del inframundo, sabia que iban a destruir todo este campamento. Por eso sali junto a Annabeth, Grover, Clarisse y otros mas a combatirlos, pero eran muy fuertes. Yo decidi seguir combatiendo, pero Cronos golpeo el suelo, y me mando volando. Luke me siguio y solto una risita: "Eres tan ridiculo" dijo con descaro. "Crees que eres tan fuerte por el hecho de ser hijo de Poseidon, pero no lo eres, sesos de alga." Tome un respiro y decidi no hablar, en verdad me tenian harto pero no valia la pena seguir peleando. Luke se abalanzo con una hoz dorada y casi me da. Yo sace a Anaklausmos y empece a luchar. La verdad fue muy reñida la batalla, pero en un punto, que ya lo tenia vencido, vi a Hades con una gran espada, apuntando a Annabeth. Grover estaba perplejo, intentaba detenerlo pero estaba amarrado a raices del inframundo. No podia dejar que eso pase, asi que corri hacia donde estaba Hades y le hice un mandoble. Hades me miro con cara de una furia intensa e invoco a las furias y a Cerbero para que se lanzen contra mi.</p> 
        
<p style="text-align: justify;">Luke me acorralo, y me señalo con su hoz dorada: "Estas perdido, Percy." Me dijo. Estaba junto a un charco de agua, asi que mi padre (Poseidon) creo una burbuja gigante para protegerme. La burbuja no duro mucho porque Ares hizo un mandoble con su lanza y revento la burbuja, estaba acabado, hasta que cree una gran serpiente con el agua, que mordio a Luke, pero Cronos se acerco, y empezo a dirigir su gran puño contra mi. Estaba cocinado, no habia salida, hasta que recorde que yo le habia robado un generador de portales a las Moiras. Por lo que lo use y me esfume. Al principio me sentia muy mal ya que habia dejado a Grover y a Annabeth solos, pero era mi unica oportunidad. Me encontraba cayendo hacia un vacio sin fin, recorrido por un gas morado que olia a pasto mojado. De repente, una corriente me arrastro fuertemente hacia un portal que me lanzo hacia un bosque gigante.</p>
        <img style="width: -webkit-fill-available; height:370px; border-radius: 30px;s" src="img/Bg.png" alt="">
    </div>
    <div>
    <p style="text-align: justify;">Estaba cayendo a una gran velocidad hacia un lago, iba a morir, debido a la altura desde la que me estaba cayendo, pero cuando aterrize resulto que el lago era profundo pero rocoso, casi golpeo mi cabeza con una roca pero logre dirigirme hacia la superficie. En cuanto vi donde estaba no me oriente. No tenia ni la menor idea donde estaba. Cuando sali del lago alcanze a leer en un cartel "Dimdrag" o "Imddagr" (mi dislexia no ayudaba) pero una voz fina y segura me hablo por detras: "Es Midgard" Yo me asuste pero resultaba ser una chica, tal vez de mi edad (16, 17 años). "Oh, lo siento" dijo la chica: "Me llamo Arianna, soy una semidiosa, porque soy hija de Heimdall, estaba aqui explorando el lago hasta que vi algo caer desde el cielo hasta este lago, pero luego me di cuenta que eras tu, cuentame, ¿que paso? Al principio fue raro que tenga tanta curiosidad, pero le explica que yo venia de otra dimension, desde Estados Unidos, pero en un mundo griego. Ella no comprendio pero le explique de que hay varias mitologias y que yo era hijo de Poseidon, el dios del mar. "¿Njord?" pregunto. "El es el dios del mar". Al parecer no entendia pero al final logro entender. </p>
            
    <p style="text-align: justify;">Ella me dijo que podia ayudarme y de que iba a llevarma a Asgard y preguntarle a Odin si podrian ellos ayudarme. El camino y nos encontramos a una gran serpiente, o dragon, o cocodrilo, no se que era, pero era gigante, de tamaño titanico, era mucho mas grande que Cronos. "Esta dormido, Jormungandr" me dijo Arianna. "Pero cuando despierta puede causar la destruccion de todo este mundo, pero la verdad va a pasar, el Ragnarok cada vez se acerca mas". Ella me explico toda la historia de la mitologia escandinava y de que era el Ragnarok. La verdad era muy tenebroso, y me daba mucho mas miedo que las hidras, furias, harpias, ciclopes, y todas las bestias juntas. En unas diez horas, llegamos a Asgard, y a el primer dios que nos encontramos fue a Freyja, y nos dijo: "¿Que hace aqui este chico?" Su tono era muy pasivo y cariñoso, me hacia acuerdo a mi madre. Arianna le explico que yo venia de otra dimension y que estaba en peligro y buscaba ayuda. Freyja entendio y acepto la propuesta con carisma: "¡Claro dulzura! ¡Como no te ayudaria! Pero hay que preguntarle a padre Odin, o si no se enojara". Comprendi y nos dirigimos hacia el castillo de Odin. En el camino, las valquirias me veian de manera rencorosa, era como que si fuese raro, o que si tuviese algo de malo. </p>
        
    <p style="text-align: justify;">¡¿Que tiene de malo un joven de pelo negro y ojos verdes!? En el sendero tambien vimos a dioses como Njord, Frigg, Tyr, Baldur, Skadi, Thor y otros mas. Todos resultaban amigables excepto uno en especifico, se llamaba Loki, y era el rey de los Jotun. Se encontraba en Asgard porque los dioses se habian reunido debido a que un gran hoyo con gas morado se habia abierto en una parte de Asgard y cada dia se engrandecia (todo me lo conto Arianna). Loki tenia un aspecto picaro y malvado, y vestia un casco dorado. Daba malas vibras y me miro fijamente con una cara de maldad, yo decidi ignorarlo y segui caminando. Ya en la puerta estaba Heimdal, a lado de dos valquirias, y el dijo: "¡Hija! ¡Quien es el!" Arianna explico mi historia una vez mas, pero esta vez Heimdal no acepto mi propuesta y se produjo una gran discusion. Finalmente, Heimdal dijo: "Esta bien, que entre, pero esto no le va a gustar a padre Odin." Arianna tenia una cara de estres y me dijo: "Perdon por mi enojo". Solto una risita. La verdad estaba incomodo, ya que me encontraba en otro lugar y no tenia idea de que hacia alli, por lo tanto solo segui a Arianna. En el trono estaba Odin sentado, y dijo: "Que desea Srta. Arianna".</p>
        
    <p style="text-align: justify;"> Arianna lucia demasiado asustada y dijo: "E-el es-s P-percy..." y le conto mi historia taartamudeando. Odin golpeo el trono: "Estas loca si crees que voy a ayudar a esa sabandija", Arianna siguio intentando convencerlo pero Odin se negaba y me grito: "¡¿Como osas a entrar en mi reino despreciable insecto?!" Yo queria callar pero un instinto me hizo gritar: "¡Estoy harto de ustedes dioses! ¡Siempre dicen con un tremendo descaro e ironia de que buscan proteger los pueblos, pero solo destruyen y destruyen! ¡¿Acaso no se apiadan de las personas!? ¡Sus propias peleas se convierten en un apocalipsis para los humanos, cuando solo deberia afectarles a ustedes!" Odin llamo a las valquirias y nos sacaron a Arianna y a mi del castillo, pero de repente se escucho un grito agonico, y provenia de Baldur. Baldur estaba sangrando y tenia una flecha que estaba, amarrado a un muerdago, y astillda en el estomago de Baldur. Loki parecia culpable pero el acuso a un ciego llamado Hodr. Los demas le creyeron y mataron al ciego. En un momento, Asgard comenzo a temblar y se rompio en varios pedazos, un gran portal me abducio y apareci en medio de la arena, demasiados escombros aparecieron a lado mio y lo raro fue de que  habia un cerebro, un muerdago, un relampago, un copo de nieve y otros elementos mas, Arianna me explico que los dioses se representan asi en otras dimensiones o para los humanos.</p>
        <img style="width: -webkit-fill-available; height:370px; border-radius: 30px;" src="img/bot-img_2.png" alt="">
    </div>
    <div>
    <p style="text-align: justify;">El lugar era de clima calido, y seco, habian piramides por todas partes y un gran pueblo estaba a la vista</p>
        <img style="width: -webkit-fill-available; height:370px; border-radius: 30px;" src="img/bot-img_3.png" alt="">
    </div>
</body>
</html>